"""Create CalendarCache table

Revision ID: 001_create_calendar_cache
Revises: 199125e575d2
Create Date: 2026-02-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_create_calendar_cache'
down_revision = '199125e575d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('events_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id')
    )
    op.create_index(op.f('ix_calendar_cache_calendar_id'), 'calendar_cache', ['calendar_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_cache_calendar_id'), table_name='calendar_cache')
    op.drop_table('calendar_cache')
    # ### end Alembic commands ###
