"""Create CalendarEventStatus table for event status tracking

Revision ID: 005_create_calendar_event_status
Revises: 004_add_calendar_fields
Create Date: 2026-02-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005_create_calendar_event_status'
down_revision = '004_add_calendar_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_uid', sa.String(length=500), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uid')
    )
    op.create_index(op.f('ix_calendar_event_status_event_date'), 'calendar_event_status', ['event_date'], unique=False)
    op.create_index(op.f('ix_calendar_event_status_event_uid'), 'calendar_event_status', ['event_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_event_status_event_date'), table_name='calendar_event_status')
    op.drop_index(op.f('ix_calendar_event_status_event_uid'), table_name='calendar_event_status')
    op.drop_table('calendar_event_status')
    # ### end Alembic commands ###
