"""Add full_name, cns, crm to User model

Revision ID: 7c790a63a956
Revises: 
Create Date: 2025-04-27 17:17:36.539547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c790a63a956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar uma nova tabela temporária com a estrutura desejada
    op.create_table(
        'users_temp',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('full_name', sa.String(length=100),
                  server_default='', nullable=False),
        sa.Column('cns', sa.String(length=15), nullable=True),
        sa.Column('crm', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
        sa.UniqueConstraint('cns', name='uq_user_cns'),
        sa.UniqueConstraint('crm', name='uq_user_crm')
    )

    # Copiar dados da tabela antiga para a nova
    op.execute('''
        INSERT INTO users_temp (id, username, password_hash, role, full_name)
        SELECT id, username, password_hash, role, '' FROM users
    ''')

    # Remover a tabela antiga
    op.drop_table('users')

    # Renomear a tabela temporária para o nome original
    op.rename_table('users_temp', 'users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar uma nova tabela temporária com a estrutura antiga
    op.create_table(
        'users_temp',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=120), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )

    # Copiar dados da tabela atual para a temporária
    op.execute('''
        INSERT INTO users_temp (id, username, password_hash, role)
        SELECT id, username, password_hash, role FROM users
    ''')

    # Remover a tabela atual
    op.drop_table('users')

    # Renomear a tabela temporária para o nome original
    op.rename_table('users_temp', 'users')

    # ### end Alembic commands ###
