"""-m

Revision ID: 199125e575d2
Revises: add_surgery_fields
Create Date: 2025-04-27 22:23:14.575923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199125e575d2'
down_revision = 'add_surgery_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('observacoes')
        batch_op.drop_column('data_prevista_cirurgia')
        batch_op.drop_column('procedimento_solicitado')
        batch_op.drop_column('cid_procedimento')

    with op.batch_alter_table('surgery_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgery_requests', schema=None) as batch_op:
        batch_op.drop_column('pdf_filename')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cid_procedimento', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('procedimento_solicitado', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('data_prevista_cirurgia', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
